version: '3.4'

services:
  nginx:
    container_name: "project-fl1.nginx"
    hostname: "nginx"
    build: docker/nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php-fpm
    ports:
      - "888:80"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      NGINX_HOST_PATH: "/var/www/html/public"
      NGINX_PHP_FPM_HOST: "project-fl1.php-fpm"
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "10"

  php-fpm:
    container_name: "project-fl1.php-fpm"
    hostname: "php-fpm"
    build: docker/php-fpm
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_BASE_PATH: /var/www/html
      SUPERVISORD_CONF: "/var/www/html/config/supervisor/*.conf"
      XDEBUG_CONFIG: "enable=${APP_DEBUG}"
      COMPOSER_MEMORY_LIMIT: -1
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "256m"
    #     max-file: "10"

  mysql:
    container_name: "project-fl1.mysql"
    hostname: "mysql"
    image: arm64v8/mysql:8
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    restart: always
    ports:
      - "3322:3306"
    volumes:
      - project_fl1_mysql_data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: project_user
      MYSQL_PASSWORD: project_pass
      MYSQL_DATABASE: project_data
      MYSQL_ROOT_PASSWORD: rootAdmin

  redis:
    container_name: "project-fl1.redis"
    hostname: "redis"
    image: redis
    restart: unless-stopped
    volumes:
      - project_fl1_redis_data:/data

  # Database - Mongo DB
  mongodb:
    container_name: "project-fl1.mongodb"
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootAdmin
    volumes:
      - ./docker/mongodb/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - project_fl1_mongodb_data:/data/db
    ports:
      - "27117:27017"

  mailhog:
    container_name: "project-fl1.mailhog"
    hostname: "mailhog"
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "2125:1025" # smtp server
      - "9125:8025" # web ui

volumes:
  project_fl1_mysql_data:
    driver: local
  project_fl1_redis_data:
    driver: local
  project_fl1_mongodb_data:
    driver: local
